#!/usr/bin/env python3
"""
Train XGBoost model using tuned hyperparameters from model_sandbox.ipynb

This script:
1. Loads features.parquet generated by dbt pipeline
2. Prepares training data (filters to labeled data only)
3. Trains XGBoost with optimized hyperparameters
4. Saves model to src/models/xgb_model_latest.pkl
5. Prints evaluation metrics

Usage:
    python scripts/train_xgboost.py
    python scripts/train_xgboost.py --input features.parquet --output src/models/xgb_model_latest.pkl
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime

try:
    import pandas as pd
    import numpy as np
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import (
        classification_report,
        confusion_matrix,
        precision_recall_curve,
        average_precision_score,
        roc_auc_score
    )
    import xgboost as xgb
    import joblib
except ImportError as e:
    print(f"ERROR: Missing required package: {e}")
    print("\nInstall dependencies:")
    print("  pip install pandas numpy scikit-learn xgboost")
    sys.exit(1)


def load_and_prepare_data(input_file: str):
    """Load features and prepare for training"""
    print("=" * 80)
    print("  Loading and Preparing Data")
    print("=" * 80)

    if not Path(input_file).exists():
        print(f"ERROR: Input file not found: {input_file}")
        print("\nRun the dbt pipeline first:")
        print("  ./scripts/run_feature_pipeline.sh")
        sys.exit(1)

    # Load features
    print(f"\nLoading: {input_file}")
    df = pd.read_parquet(input_file)
    print(f"  Total rows: {len(df):,}")
    print(f"  Total columns: {len(df.columns)}")

    # Show label distribution
    print("\nLabel distribution (all data):")
    print(df['label_source'].value_counts())

    # Filter to labeled data only (exclude 'unknown')
    print("\nFiltering to labeled data only...")
    df_labeled = df[df['label_source'] != 'unknown'].copy()
    print(f"  Labeled rows: {len(df_labeled):,}")

    if len(df_labeled) == 0:
        print("\nERROR: No labeled data found!")
        print("Make sure you have phishtank (y=1) and tranco (y=0) labels in your data.")
        sys.exit(1)

    print("\nLabel distribution (labeled only):")
    print(df_labeled['y'].value_counts())
    print(f"  Phishing (y=1): {(df_labeled['y'] == 1).sum():,}")
    print(f"  Legitimate (y=0): {(df_labeled['y'] == 0).sum():,}")

    # Define feature columns (exclude identifiers, labels, metadata)
    exclude_cols = [
        'fingerprint', 'serial', 'domain', 'timestamp',
        'not_before', 'not_after', 'issuer_org', 'tld',
        'closest_brand', 'y', 'label_source', 'label_timestamp',
        'source', 'data_source'
    ]

    feature_cols = [col for col in df_labeled.columns if col not in exclude_cols]

    print(f"\nFeature columns ({len(feature_cols)}):")
    for col in feature_cols:
        print(f"  - {col}")

    # Prepare X and y
    X = df_labeled[feature_cols].copy()
    y = df_labeled['y'].copy()

    # Handle any missing values (fill with 0)
    if X.isnull().any().any():
        print("\nWarning: Found missing values, filling with 0")
        X = X.fillna(0)

    # Handle infinite values
    X = X.replace([np.inf, -np.inf], 0)

    return X, y, feature_cols


def train_model(X, y, feature_cols):
    """Train XGBoost with tuned hyperparameters"""
    print("\n" + "=" * 80)
    print("  Training XGBoost Model")
    print("=" * 80)

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    print(f"\nTrain set: {len(X_train):,} samples")
    print(f"  Phishing: {(y_train == 1).sum():,}")
    print(f"  Legitimate: {(y_train == 0).sum():,}")

    print(f"\nTest set: {len(X_test):,} samples")
    print(f"  Phishing: {(y_test == 1).sum():,}")
    print(f"  Legitimate: {(y_test == 0).sum():,}")

    # Calculate scale_pos_weight
    n_neg = (y_train == 0).sum()
    n_pos = (y_train == 1).sum()
    scale_pos_weight = n_neg / n_pos if n_pos > 0 else 1.0

    print(f"\nClass balance:")
    print(f"  scale_pos_weight: {scale_pos_weight:.2f}")

    # Tuned hyperparameters from model_sandbox.ipynb
    print("\nHyperparameters (tuned for recall):")
    params = {
        'n_estimators': 300,
        'max_depth': 3,
        'learning_rate': 0.2,
        'subsample': 0.8,
        'colsample_bytree': 0.8,
        'scale_pos_weight': scale_pos_weight,
        'eval_metric': 'aucpr',
        'random_state': 42,
        'n_jobs': -1
    }

    for param, value in params.items():
        print(f"  {param}: {value}")

    # Train model
    print("\nTraining XGBoost...")
    start_time = datetime.now()

    model = xgb.XGBClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_test, y_test)],
        verbose=False
    )

    train_time = (datetime.now() - start_time).total_seconds()
    print(f"✅ Training complete! ({train_time:.1f} seconds)")

    # Evaluate model
    print("\n" + "=" * 80)
    print("  Model Evaluation")
    print("=" * 80)

    # Predictions
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]

    # Metrics
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=['Legitimate', 'Phishing']))

    print("\nConfusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    print(f"\nTrue Negatives (TN):  {cm[0][0]:,}")
    print(f"False Positives (FP): {cm[0][1]:,}")
    print(f"False Negatives (FN): {cm[1][0]:,}")
    print(f"True Positives (TP):  {cm[1][1]:,}")

    # Additional metrics
    precision = cm[1][1] / (cm[1][1] + cm[0][1]) if (cm[1][1] + cm[0][1]) > 0 else 0
    recall = cm[1][1] / (cm[1][1] + cm[1][0]) if (cm[1][1] + cm[1][0]) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    ap_score = average_precision_score(y_test, y_pred_proba)
    roc_auc = roc_auc_score(y_test, y_pred_proba)

    print("\nKey Metrics:")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f} ⭐")
    print(f"  F1 Score:  {f1:.4f}")
    print(f"  Avg Precision (AP): {ap_score:.4f}")
    print(f"  ROC AUC:   {roc_auc:.4f}")

    # Feature importance
    print("\n" + "=" * 80)
    print("  Top 10 Most Important Features")
    print("=" * 80)

    feature_importance = pd.DataFrame({
        'feature': feature_cols,
        'importance': model.feature_importances_
    }).sort_values('importance', ascending=False)

    for idx, row in feature_importance.head(10).iterrows():
        print(f"  {row['feature']:25s}: {row['importance']:.4f}")

    return model, {
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'ap_score': ap_score,
        'roc_auc': roc_auc,
        'train_samples': len(X_train),
        'test_samples': len(X_test),
        'train_time_seconds': train_time
    }


def save_model(model, feature_cols, metrics, output_file: str):
    """Save trained model to pickle file"""
    print("\n" + "=" * 80)
    print("  Saving Model")
    print("=" * 80)

    # Create output directory if needed
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save model with metadata
    model_data = {
        'model': model,
        'feature_cols': feature_cols,
        'metrics': metrics,
        'trained_at': datetime.now().isoformat(),
        'hyperparameters': {
            'n_estimators': model.n_estimators,
            'max_depth': model.max_depth,
            'learning_rate': model.learning_rate,
            'subsample': model.subsample,
            'colsample_bytree': model.colsample_bytree,
            'scale_pos_weight': model.scale_pos_weight
        }
    }

    joblib.dump(model_data, output_file)

    # Get file size
    size_mb = output_path.stat().st_size / (1024 * 1024)

    print(f"\n✅ Model saved: {output_file}")
    print(f"   Size: {size_mb:.2f} MB")
    print(f"   Features: {len(feature_cols)}")
    print(f"   Recall: {metrics['recall']:.4f}")
    print(f"   AP Score: {metrics['ap_score']:.4f}")


def main():
    parser = argparse.ArgumentParser(
        description="Train XGBoost model with tuned hyperparameters"
    )
    parser.add_argument(
        "--input",
        default="features.parquet",
        help="Path to features parquet file (default: features.parquet)"
    )
    parser.add_argument(
        "--output",
        default="src/models/xgb_model_latest.pkl",
        help="Path to save trained model (default: src/models/xgb_model_latest.pkl)"
    )

    args = parser.parse_args()

    print("=" * 80)
    print("  XGBoost Training Pipeline")
    print("=" * 80)
    print(f"\nInput:  {args.input}")
    print(f"Output: {args.output}")
    print()

    # Load and prepare data
    X, y, feature_cols = load_and_prepare_data(args.input)

    # Train model
    model, metrics = train_model(X, y, feature_cols)

    # Save model
    save_model(model, feature_cols, metrics, args.output)

    print("\n" + "=" * 80)
    print("  ✅ Training Complete!")
    print("=" * 80)
    print()


if __name__ == "__main__":
    main()
